### PR TITLE
[NOT READY FOR MERGE] VS2015 x64 Compatibility

### PR DESCRIPTION
**Pull request by mattfelsen**
Wanted to get this PR on the books in case anyone else is looking for vs2015/x64 support (or wants to help!). This is currently working with the command line projectGenerator**, but a couple things should happen before merging:

- [x] fix addon_config.mk so correct libs are added for Win32/x64 in both Debug/Release
- [x] add libwebsockets compile instructions to readme
- [ ] verify SSL support is functional
- [ ] create VS project/property sheet

Example projects:
- [ ] Update example_client_blob (Need to check ofxTurboJpeg)
- [x] Update example_client_hello_world
- [x] ~~Update example_client_ios~~ (No update needed)
- [x] Update example_client_sharedcanvas
- [ ] Update example_particles_client
- [ ] Update example_particles_server
- [x] Update example_server_binary
- [x] Update example_server_binary_video
- [ ] Update example_server_blob (Need to check ofxTurboJpeg)
- [ ] Update example_server_blobvideo (Need to check ofxTurboJpeg)
- [x] Update example_server_echo
- [x] Update example_server_sharedcanvas

** Before running the pg I renamed addon_config.mk so that it wasn't used to parse the addon libs to be added. Currently for vs, the pg will only add the Win32/Release libs as per the file; without the config file the projectGenerator will correctly add all the libs by parsing the folder structure. Should we remove the ADDON_LIBS section & let the pg do it's thang, or manually write out the necessary stuff?

### CODE REVIEW

**Comment by robotconscience** [comment]
Awesome! Thanks for taking a crack at this. Hoping to have a moment today to look at it.
I don't really understand what's up with the PG and Debug/Release/32/64. I thought it all had to be in addon_config, but looking at the src a bit it appears it's more magic within the app. 

My pref would be to put all the stuff in the addon_config so people understand it, then comment it out and let PG do its thing. Does that make sense? I want to have the stuff there so people understand what they need to include if they're manually building the project, but know that most people (myself included) will just use the PG. Cool?

**Comment by mattfelsen** [comment]
Take a look at the discussion on this issue: https://github.com/openframeworks/openFrameworks/issues/4241#issuecomment-130775940

I don't really understand why this only became a problem recently, but apparently Visual Studio doesn't like linking against debug libs for a release build? So the solution a few months ago was to change the folder structure for an addon's libs into:

- ADDON_ROOT/libs/somelibrary/lib/vs/Win32/Debug
- ADDON_ROOT/libs/somelibrary/lib/vs/Win32/Release
- ADDON_ROOT/libs/somelibrary/lib/vs/x64/Debug
- ADDON_ROOT/libs/somelibrary/lib/vs/x64/Release

There's still the ability to specify things on a per-target basis, but it looks like the granularity there is just "vs" -- no ability to specify Win32 vs x64 nor Debug vs. Release libs (historically it looks like the pg used to look for the lib's filename ending in "d" which they realized was not a great solution :smile: ). Instead, the pg now parses that info from the folder structure, so that's what I've done in the first commit. I like your thinking with putting it in add_config.mk but commented out so people can follow, but since the specificity for architecture and mode isn't there I don't see how we could do that.

Interestingly, I just tried creating a release build by pointing at the debug libs, and it compiled & ran fine (after a clean build). So I guess that begs the question of whether we need to include debug libs at all?

**Comment by mattfelsen** [comment]
Forgot to add: while that discussion included that adding the ability to addon_config.mk makes sense and the folder structure could be optional, only the latter got implemented and the issue so closed. Sooo... :stuck_out_tongue_closed_eyes:

**Comment by mattfelsen** [comment]
1) Done!
2) Can do!
3) Ditto! This was foreign to me at first, but seeing it on...
  - ofxKinectForWindows2
  - [ofxCv](https://github.com/kylemcdonald/ofxCv/tree/VS2012-static/ofxCvLib) (also by Elliot, surprise, surprise) 
  - [PCL](http://unanancyowen.com/?p=1255&lang=en) for PCL, OpenNI, and Kinect libs

...is like whoa. Really helpful! It's a shame it's not more widely used in OF. Seems like addon_config.mk is essentially a duplicate effort, though I suppose the reason is it's not platform- or IDE-specific. 

I had a feeling you were into it after seeing #41 :stuck_out_tongue_closed_eyes: I'll give it a shot soon. And adding it to the checklist above.

**Comment by robotconscience** [comment]
Awesome, thanks Matt! Keep me posted.

**Comment by mattfelsen** [comment]
Small update here...I'm seeing weird behavior when trying to send any binary data. Seems like the video grabber & player aren't working on Windows at the moment, so it's making it annoying to test the binary_video example, but even with the binary example (the image drag & drop one), I'm not getting images in the browser. Usually the browser gets disconnected when I drag on an image...sometimes not but it never appears. Seeing this for both x86/x64, so maybe it's a Windows issue/firewall thing rather than something specific to the x64 libs. No crashes/weird output on the OF side, no JS errors in the console in the browser. Gonna try and dig a bit deeper, but wondering if the same thing happens for you?

**Comment by robotconscience** [comment]
Haven't dug in yet, hope to later today or tomorrow.
@quinkennedy any chance you can give it a shot on Windows?

**Comment by robotconscience** [comment]
Quick Q: does the binary blob example work? Or do you mean all of the binary examples?

**Comment by mattfelsen** [comment]
The blob examples use ofxTurboJpeg which I thought was 32-bit only, so I haven't looked at those yet – I'm seeing this in the binary/video examples as well as the particle ones – though I don't even see particles on screen in the server's window so I think there's some other stuff going on with that one.

**Comment by mattfelsen** [comment]
Alright, another small update...turns out the images *do* appear, but super slowly. I'm talking ~15-30s for a 30k image, and ~60s+ for a 100k image. The blob example works (32-bit) and is faster, maybe a couple seconds for a small image, but still laggy (I verified it's nearly-instant on OSX like I expected it should be). I thought maybe it was Chrome, but I'm seeing the same in a quick OF client app, and also the same on 0.8.4/VS2012. I'm guessing it's some weird Windows voodoo at play, or maybe a bug in libwebsockets. I'll try to test on libwebsockets 1.4 just for kicks, and maybe Windows 10 but I don't have that installed anywhere currently... :confused:

**Comment by robotconscience** [comment]
That's not super surprising–the binary example is sort of hack-y, as the blob way is the "right" way to do it, really.
I wonder if there's a 64-bit compiled turbo-jpeg floating around somewhere? Care to open another pull request? ;)

**Comment by robotconscience** [comment]
Ha, not sure why monster frown ended up in there!

**Comment by mattfelsen** [comment]
Yeeaaaa I was thinking I'd have to bite the 64-bit turbo-jpeg bullet. There are actually official binaries available -- do you know why @tgfrerer had to recompile from source? Was it to get the debug library?

**Comment by robotconscience** [comment]
Not sure! It's super easy to compile, though, especially with cmake gui as
he describes.

On Tue, Oct 20, 2015 at 11:59 AM Matt Felsen <notifications@github.com>
wrote:

> Yeeaaaa I was thinking I'd have to bite the 64-bit turbo-jpeg bullet.
> There are actually official binaries available -- do you know why
> @tgfrerer <https://github.com/tgfrerer> had to recompile from source? Was
> it to get the debug library?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/labatrockwell/ofxLibwebsockets/pull/63#issuecomment-149615507>
> .
>
-- 
Brett Renfer
\\ robotconscience.com
// tsps.cc

**Comment by mattfelsen** [comment]
Hrm...I see what you mean about sending pixels + the w/h/type string vs. sending compressed jpeg data. I modified the blob example to use `ofLoadImage/ofSaveImage` instead of `turbo.load/turbo.compress` and they're both about ~8s for a 112k image, so I don't think it's bandwidth (I'm running client & server on the same machine after all) or speed of compression...I'll try to get turbo updated for x64 anyways since that seems useful and let you know what else I find :scream:

**Comment by mattfelsen** [comment]
[PR for 64-bit turbo-jpeg is here](https://github.com/robotconscience/ofxTurboJpeg/pull/2) but no dice on speedups. The search continues...

**Comment by robotconscience** [comment]
Dang! That's crazy. Anything on libwebsockets RE: binary sending? I did a refactor of that not too long ago, not sure what else to do!

**Comment by mattfelsen** [comment]
:)

**Comment by mattfelsen** [comment]
I never got to the root of the slow speed thing, but I am fairly certain it's Windows and not lws. I'll send along updated vs project files for the remaining examples soon!

**Comment by robotconscience** [comment]
I'm on it! Jamming through it all this AM.
On Fri, Nov 13, 2015 at 10:06 AM Matt Felsen <notifications@github.com>
wrote:

> I never got to the root of the slow speed thing, but I am fairly certain
> it's Windows and not lws. I'll send along updated vs project files for the
> remaining examples soon!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/labatrockwell/ofxLibwebsockets/pull/63#issuecomment-156456080>
> .
>
-- 
Brett Renfer
\\ robotconscience.com
// tsps.cc

**Comment by mattfelsen** [comment]
Cool – curious if you see the same issues or not. Keep me posted! (Even though I'm not currently working on any Windows stuff anymore 😉)

**Pull request merged**
