### PR TITLE
Updated lws library and fix for RPI(2)

### PR DESCRIPTION
**Pull request by PTS93**
https://github.com/labatrockwell/ofxLibwebsockets/issues/52#issuecomment-101717263

### CODE REVIEW

**Comment by robotconscience** [comment]
Fantastic! I'll merge this in once I update libwebsockets for win and osx. Nice work!

**Comment by PTS93** [comment]
Cool, I see if i can quickly boot my image on a PI1 and build the lib for arm6 aswell.

**Comment by PTS93** [comment]
Whoops, thought that was the issue thread.

**Comment by PTS93** [comment]
Added binary for armv6l. Compiled on an old RPi B+.

**Pull request merged**
